version: '3.7'

services:
  sleep-service:
    container_name: sleep-service
    build:
      context: ./sleep-service
    volumes:
      - ./sleep-service:/usr/src/app
    ports:
      - 8080:8080
    networks:
      - webnet
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2-bionic
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodata:/data/db
    networks:
      - webnet
networks:
  webnet:
volumes:
  mongodata:
